id: Recorded Future Leaked Credential Alert Handling
version: -1
name: Recorded Future Leaked Credential Alert Handling
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9bb8e2cb-f516-4211-8d30-c68e96e56cba
    type: start
    task:
      id: 9bb8e2cb-f516-4211-8d30-c68e96e56cba
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 120524b6-0942-47a2-8fc8-04c8b108612d
    type: playbook
    task:
      id: 120524b6-0942-47a2-8fc8-04c8b108612d
      version: -1
      name: Account Enrichment - Generic v2.1
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
      playbookName: Account Enrichment - Generic v2.1
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      Username:
        complex:
          root: incident.recordedfuturealertentities
          accessor: name
          transformers:
          - operator: uniq
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 0446baef-f96d-4e57-8313-86a7da5e6932
    type: condition
    task:
      id: 0446baef-f96d-4e57-8313-86a7da5e6932
      version: -1
      name: Is the user account active?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "YES":
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 058b225b-c150-4fe1-82d5-72745147fcb7
    type: regular
    task:
      id: 058b225b-c150-4fe1-82d5-72745147fcb7
      version: -1
      name: Query SIEM for suspicious behavior, logins, and location
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 710,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7a942360-05a1-439d-85cb-e150ae1b26ed
    type: regular
    task:
      id: 7a942360-05a1-439d-85cb-e150ae1b26ed
      version: -1
      name: Add note to Recorded Future alert
      description: Set a note for the alert in Recorded Future
      script: Recorded Future v2|||recordedfuture-alert-set-note
      type: regular
      iscommand: true
      brand: Recorded Future v2
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      alert_id:
        simple: ${incident.alertid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 360,
          "y": 1600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: bcfa60cc-c41f-4231-8177-2d595fa78433
    type: regular
    task:
      id: bcfa60cc-c41f-4231-8177-2d595fa78433
      version: -1
      name: Notify user
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 710,
          "y": 705
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: a85bd591-178b-4e15-8dac-2cac53771955
    type: regular
    task:
      id: a85bd591-178b-4e15-8dac-2cac53771955
      version: -1
      name: Expire password
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: e629dfc3-46aa-485a-8017-3b104f6c9751
    type: regular
    task:
      id: e629dfc3-46aa-485a-8017-3b104f6c9751
      version: -1
      name: Close the Incident
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 360,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 6bf1fb31-b094-4970-843e-734b9be9c39c
    type: condition
    task:
      id: 6bf1fb31-b094-4970-843e-734b9be9c39c
      version: -1
      name: Verify activity
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "YES":
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 710,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 59020c1c-d3ba-498a-817f-6198431031e7
    type: regular
    task:
      id: 59020c1c-d3ba-498a-817f-6198431031e7
      version: -1
      name: |
        Disable account
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 55b731a0-a7f4-4574-829b-dbe9f501747d
    type: regular
    task:
      id: 55b731a0-a7f4-4574-829b-dbe9f501747d
      version: -1
      name: Enable account
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "8_4_YES": 0.41
    },
    "paper": {
      "dimensions": {
        "height": 1815,
        "width": 900,
        "x": 360,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.5.0
description: ""
