id: Recorded Future Vulnerability Alert Handling
version: -1
name: Recorded Future Vulnerability Alert Handling
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5fe7d07b-9e8e-422c-813a-4a20149202db
    type: start
    task:
      id: 5fe7d07b-9e8e-422c-813a-4a20149202db
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 63717507-bf6f-4701-8236-66a617f7ca65
    type: regular
    task:
      id: 63717507-bf6f-4701-8236-66a617f7ca65
      version: -1
      name: Enrich CVE Data
      description: Get threat intelligence for an IP, Domain, CVE, URL or File.
      script: '|||recordedfuture-intelligence'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      entity:
        simple: ${incident.recordedfuturealertentities.name}
      entity_type:
        simple: cve
      fetch_related_entities:
        simple: "no"
      fetch_riskyCIDRips:
        simple: "no"
      profile:
        simple: Vulnerability Analyst
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 460a35ed-5ced-4c00-8028-30c5831d2101
    type: regular
    task:
      id: 460a35ed-5ced-4c00-8028-30c5831d2101
      version: -1
      name: Recorded Future Technical Links
      description: Get Insikt Group Research Links for an IP, Domain, CVE, URL or File.
      script: Recorded Future v2|||recordedfuture-links
      type: regular
      iscommand: true
      brand: Recorded Future v2
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      entity:
        simple: ${incident.recordedfuturealertentities.name}
      entity_type:
        simple: cve
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b213eb1c-330f-48c4-868c-6501b8fced83
    type: regular
    task:
      id: b213eb1c-330f-48c4-868c-6501b8fced83
      version: -1
      name: Compare CVE list with internal vuln data
      description: ""
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 5abd364f-b167-4684-8541-7b69eb57d853
    type: title
    task:
      id: 5abd364f-b167-4684-8541-7b69eb57d853
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 725
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 740,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- Recorded Future Test Playbook
fromversion: 6.5.0
description: ""
